### ISSUE TITLE
IMapTo interface has source/destination mixed up in LoadStandardMappings

### ISSUE THREAD

**Issue by AndriusPreibys** [threenine/Threenine.Map#1]
Tried a super simple console app and got "Missing type map configuration or unsupported mapping" error.

```
    class Program
    {
        static void Main(string[] args)
        {
            MapConfigurationFactory.Scan<Program>();
            var objA = new ClassA { Field = 1 };
            var objB = Mapper.Map<ClassB>(objA);
        }
    }

    public class ClassA: IMapTo<ClassB>
    {
        public int Field { get; set; }
    }

    public class ClassB
    {
        public int Field { get; set; }
    }
```

**Comment by garywoodfine** [comment]
``` csharp
using System;
using AutoMapper;
using Threenine.Map;

namespace SimpleMappingFactory
{
    class Program
    {
        static void Main(string[] args)
        {
            MapConfigurationFactory.Scan<Program>();

            var testMap = new ClassA {Name = "Gary"};

            var testMap2 = Mapper.Map<ClassB>(testMap);
                
            Console.WriteLine(testMap2.Name);
            Console.WriteLine(testMap2.GetType().Name);
        }
    }
}
```
```csharp
using Threenine.Map;

namespace SimpleMappingFactory
{
    public class ClassA : IMapTo<ClassB> 
    {
        public string  Name { get; set; }
    }
}
```

```csharp
using Threenine.Map;

namespace SimpleMappingFactory
{
    public class ClassB 
    {
        public string  Name { get; set; }
    }
}
````

Works fine no issues.  You'll find a zip of the super simple project I created, testing out the mapping.
Hope this helps

[SimpleMappingFactory.zip](https://github.com/threenine/Threenine.Map/files/4021807/SimpleMappingFactory.zip)

**Comment by AndriusPreibys** [comment]
Thanks for your prompt reply.
Strange - your code still does not work on my machine (same issue). I use AutoMapper 8.1.1 and  Threenine.Map 1.0.3. I added [public repo](https://github.com/AndriusPreibys/ThreenineMapTest) if you would like to check it out.

**Comment by garywoodfine** [comment]
@AndriusPreibys  Check out my previous reply I added a zip of a sample project

**Comment by AndriusPreibys** [comment]
Thanks, it works fine with AutoMapper 8.0.0 but breaks with 8.1.1 - this is probably due to static mapper being deprecated https://github.com/AutoMapper/AutoMapper/pull/3082 (strange that IMapFrom works just fine).

Edited: it is probably because "Deprecate CreateMissingTypeMaps and change the default to false" https://github.com/AutoMapper/AutoMapper/releases/tag/v8.1.1

**Comment by garywoodfine** [comment]
I have only tested and developed for automapper 8.0, that is what the dependency  the nuget package comes prepacked with.

**Comment by itsamaik** [comment]
> Thanks, it works fine with AutoMapper 8.0.0 but breaks with 8.1.1 - this is probably due to static mapper being deprecated [AutoMapper/AutoMapper#3082](https://github.com/AutoMapper/AutoMapper/pull/3082) (strange that IMapFrom works just fine).
> 
> Edited: it is probably because "Deprecate CreateMissingTypeMaps and change the default to false" https://github.com/AutoMapper/AutoMapper/releases/tag/v8.1.1

This is correct, I've noticed the same. Would be a good fix to include.
